### ISSUE TITLE
NPM package being used?

### ISSUE THREAD

**Issue by jrbotros** [alligator-io/alligator#1]
We're currently looking to open-source a project over at [B12](github.com/b12io) and wanted to name it `alligator` as well. Is this package still actively used? If not, could you transfer the npm rights to us? Thanks in advance for your consideration!

**Comment by alligator-io** [comment]
I'm sorry, I can't give the name. I'm still working on this project

**Comment by jrbotros** [comment]
No problem, thanks for letting me know!
